#include "config.h"

#include "common.h"
#include "scout_files.h"

#include <stdio.h>
#include <string.h>

int scout_write_lease_file(const char *path, const scout_iface_t *iface, const scout_lease_t *lease)
{
    char contents[2048];
    char addr[32];
    char mask[32];
    char router[32];
    char server[32];
    char dns_lines[256];
    size_t offset = 0;
    size_t i;

    dns_lines[0] = '\0';
    for (i = 0; i < lease->dns_count; ++i) {
        char dns[32];
        scout_format_ipv4(lease->dns[i], dns, sizeof(dns));
        offset += (size_t)snprintf(dns_lines + offset, sizeof(dns_lines) - offset,
                                   "%sdns%zu=%s\n", offset ? "" : "", i + 1u, dns);
        if (offset >= sizeof(dns_lines)) {
            break;
        }
    }

    scout_format_ipv4(lease->address, addr, sizeof(addr));
    scout_format_ipv4(lease->subnet_mask, mask, sizeof(mask));
    scout_format_ipv4(lease->router, router, sizeof(router));
    scout_format_ipv4(lease->server_id, server, sizeof(server));

    snprintf(contents, sizeof(contents),
             "interface=%s\n"
             "address=%s\n"
             "netmask=%s\n"
             "gateway=%s\n"
             "server_id=%s\n"
             "lease_time=%u\n"
             "renewal_time=%u\n"
             "rebind_time=%u\n"
             "obtained_at=%ld\n"
             "domain=%s\n"
             "%s",
             iface->name,
             addr,
             mask,
             router,
             server,
             lease->lease_time,
             lease->renewal_time,
             lease->rebind_time,
             (long)lease->obtained_at,
             lease->domain,
             dns_lines);

    return scout_write_text_file_atomic(path, contents);
}

int scout_write_resolv_conf(const char *path, const scout_lease_t *lease)
{
    char contents[1024];
    size_t offset = 0;
    size_t i;

    offset += (size_t)snprintf(contents + offset, sizeof(contents) - offset,
                               "# Generated by scout\n");
    if (lease->domain[0] != '\0') {
        offset += (size_t)snprintf(contents + offset, sizeof(contents) - offset,
                                   "search %s\n", lease->domain);
    }
    for (i = 0; i < lease->dns_count && offset < sizeof(contents); ++i) {
        char dns[32];
        scout_format_ipv4(lease->dns[i], dns, sizeof(dns));
        offset += (size_t)snprintf(contents + offset, sizeof(contents) - offset,
                                   "nameserver %s\n", dns);
    }
    offset += (size_t)snprintf(contents + offset, sizeof(contents) - offset,
                               "options timeout:2 attempts:2\n");

    return scout_write_text_file_atomic(path, contents);
}

int scout_write_interfaces_snapshot(const char *path, const scout_iface_t *iface, const scout_lease_t *lease)
{
    char addr[32];
    char mask[32];
    char router[32];
    char contents[1200];
    char dns[96] = "";
    size_t i;
    size_t offset = 0;

    scout_format_ipv4(lease->address, addr, sizeof(addr));
    scout_format_ipv4(lease->subnet_mask, mask, sizeof(mask));
    scout_format_ipv4(lease->router, router, sizeof(router));

    for (i = 0; i < lease->dns_count && offset < sizeof(dns); ++i) {
        char item[32];
        scout_format_ipv4(lease->dns[i], item, sizeof(item));
        offset += (size_t)snprintf(dns + offset, sizeof(dns) - offset, "%s%s",
                                   i == 0 ? "" : " ", item);
    }

    snprintf(contents, sizeof(contents),
             "auto lo\n"
             "iface lo inet loopback\n"
             "\n"
             "auto %s\n"
             "iface %s inet static\n"
             "    address %s\n"
             "    netmask %s\n"
             "%s%s%s"
             "%s%s%s",
             iface->name,
             iface->name,
             addr,
             mask,
             lease->router ? "    gateway " : "",
             lease->router ? router : "",
             lease->router ? "\n" : "",
             dns[0] ? "    dns-nameservers " : "",
             dns[0] ? dns : "",
             dns[0] ? "\n" : "");
    return scout_write_text_file_atomic(path, contents);
}
